name: Get INR Value

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    scrapecurrency:
        runs-on: ubuntu-latest
        permission:
            contents: write
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install Dependencies
              run: pip install requests beautifulsoup4
            - name: Run Script
              run: python script.py
            - name: Push it to GitHub
              run: |
                  git config --global user.email "symplifyinstructors@gmail.com"
                  git config --global user.name "symplifygh"
                  git add .
                  git commit -m "Automated update"
                  git push
